### ISSUE TITLE
In Oreo os 8.0.0. Device: SM-N950F gettting the crash

### ISSUE THREAD

**Issue by hardikpatel679** [ParkSangGwon/TedPermission#88]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6940)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by hardikpatel679** [comment]
just change the style <item name="android:windowIsTranslucent">true</item> to  <item name="android:windowIsTranslucent">false</item>

**Comment by ps-jimmy** [comment]
This solution works for me:  

  <activity android:name="com.gun0912.tedpermission.TedPermissionActivity"            android:configChanges="mcc|mnc|locale|keyboard|keyboardHidden|screenLayout|fontScale|uiMode|orientation|screenSize|layoutDirection"
            android:screenOrientation="unspecified"
            android:theme="@style/Theme.Transparent.Permission"
            tools:replace="android:screenOrientation"/>

**Comment by ParkSangGwon** [comment]
This issue solved at #74

**Comment by Jitesh1720** [comment]
> This issue solved at #74

I still facing this issue.

> <item name="android:windowIsTranslucent">false</item>

Applied this in theme/style

is the issue related with orientation ?
currently my project orientation is landscape 

> android:screenOrientation="landscape"

**Comment by hardikpatel679** [comment]
Bro if you had write orientation in Mimifirst file then remove it and chek

**Comment by Jitesh1720** [comment]
Yeah right. if I remove orientation from manifest then its working.
But It compulsory for my app so I just update version to `2.2.2` and ArrayList to List. Now its working in Oreo with screen orientation in manifest.

```
@Override
        public void onPermissionDenied(ArrayList<String> deniedPermissions) {
        }
```

```
@Override
        public void onPermissionDenied(List<String> deniedPermissions) {
        }
```

Anyway. Thanks for your support.

**Comment by hardikpatel679** [comment]
Issue is that if you use transperent activity the donot provide orientation
in Oreo.
